/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppResponse {
    #[serde(rename = "totalProducts")]
    pub total_products: i32,
    #[serde(rename = "products")]
    pub products: Vec<models::Product>,
}

impl AppResponse {
    pub fn new(total_products: i32, products: Vec<models::Product>) -> AppResponse {
        AppResponse {
            total_products,
            products,
        }
    }
}
