/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Order {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "customer_id")]
    pub customer_id: f64,
    #[serde(rename = "line_items")]
    pub line_items: Vec<models::OrderLineItem>,
    #[serde(rename = "billing")]
    pub billing: Box<models::OrderBilling>,
}

impl Order {
    pub fn new(
        id: i32,
        status: String,
        customer_id: f64,
        line_items: Vec<models::OrderLineItem>,
        billing: models::OrderBilling,
    ) -> Order {
        Order {
            id,
            status,
            customer_id,
            line_items,
            billing: Box::new(billing),
        }
    }
}
