/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderLineItem {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "product_id")]
    pub product_id: i32,
    #[serde(rename = "variation_id")]
    pub variation_id: i32,
    #[serde(rename = "quantity")]
    pub quantity: i32,
    #[serde(rename = "image")]
    pub image: serde_json::Value,
}

impl OrderLineItem {
    pub fn new(
        id: i32,
        status: String,
        product_id: i32,
        variation_id: i32,
        quantity: i32,
        image: serde_json::Value,
    ) -> OrderLineItem {
        OrderLineItem {
            id,
            status,
            product_id,
            variation_id,
            quantity,
            image,
        }
    }
}
