/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostApiV2Tokens200ResponseData {
    #[serde(rename = "token")]
    pub token: Box<models::PostApiV2Tokens200ResponseDataToken>,
}

impl PostApiV2Tokens200ResponseData {
    pub fn new(
        token: models::PostApiV2Tokens200ResponseDataToken,
    ) -> PostApiV2Tokens200ResponseData {
        PostApiV2Tokens200ResponseData {
            token: Box::new(token),
        }
    }
}
