/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostApiV2Tokens200ResponseDataToken {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "password")]
    pub password: String,
}

impl PostApiV2Tokens200ResponseDataToken {
    pub fn new(username: String, password: String) -> PostApiV2Tokens200ResponseDataToken {
        PostApiV2Tokens200ResponseDataToken { username, password }
    }
}
