/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductStore {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "shop_name")]
    pub shop_name: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "address")]
    pub address: Box<models::Address>,
}

impl ProductStore {
    pub fn new(
        id: i32,
        name: String,
        shop_name: String,
        url: String,
        address: models::Address,
    ) -> ProductStore {
        ProductStore {
            id,
            name,
            shop_name,
            url,
            address: Box::new(address),
        }
    }
}
