/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Product {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "short_description")]
    pub short_description: String,
    #[serde(rename = "average_rating")]
    pub average_rating: String,
    #[serde(rename = "rating_count")]
    pub rating_count: i32,
    #[serde(rename = "categories")]
    pub categories: Vec<models::ProductCategory>,
    #[serde(rename = "attributes")]
    pub attributes: Vec<models::ProductAttribute>,
    #[serde(rename = "meta_data")]
    pub meta_data: Vec<models::ProductMetadata>,
    #[serde(rename = "stock_status")]
    pub stock_status: String,
    #[serde(rename = "store")]
    pub store: Box<models::ProductStore>,
    #[serde(rename = "permalink")]
    pub permalink: String,
    #[serde(rename = "price")]
    pub price: String,
    #[serde(rename = "purchasable")]
    pub purchasable: bool,
}

impl Product {
    pub fn new(
        id: i32,
        name: String,
        status: String,
        description: String,
        short_description: String,
        average_rating: String,
        rating_count: i32,
        categories: Vec<models::ProductCategory>,
        attributes: Vec<models::ProductAttribute>,
        meta_data: Vec<models::ProductMetadata>,
        stock_status: String,
        store: models::ProductStore,
        permalink: String,
        price: String,
        purchasable: bool,
    ) -> Product {
        Product {
            id,
            name,
            status,
            description,
            short_description,
            average_rating,
            rating_count,
            categories,
            attributes,
            meta_data,
            stock_status,
            store: Box::new(store),
            permalink,
            price,
            purchasable,
        }
    }
}
