/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductResponse {
    #[serde(rename = "page")]
    pub page: i32,
    #[serde(rename = "totalPages")]
    pub total_pages: i32,
    #[serde(rename = "products")]
    pub products: Vec<models::Product>,
}

impl ProductResponse {
    pub fn new(page: i32, total_pages: i32, products: Vec<models::Product>) -> ProductResponse {
        ProductResponse {
            page,
            total_pages,
            products,
        }
    }
}
