/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReviewResponse {
    #[serde(rename = "review")]
    pub review: Box<models::ReviewResponseReview>,
}

impl ReviewResponse {
    pub fn new(review: models::ReviewResponseReview) -> ReviewResponse {
        ReviewResponse {
            review: Box::new(review),
        }
    }
}
