/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Subscriptions {
    #[serde(rename = "totalSubscriptions")]
    pub total_subscriptions: i32,
    #[serde(rename = "subscriptions")]
    pub subscriptions: Vec<models::Order>,
}

impl Subscriptions {
    pub fn new(total_subscriptions: i32, subscriptions: Vec<models::Order>) -> Subscriptions {
        Subscriptions {
            total_subscriptions,
            subscriptions,
        }
    }
}
